export const RESPONSE_OK = 200;
export const RESPONSE_BAD_REQUEST = 400;
export const RESPONSE_NOT_FOUND = 404;
export const RESPONSE_INTERNAL_SERVER_ERROR = 500;
export const RESPONSE_NOT_IMPLEMENTED = 501;
